const allSounds = {
    KeyZ:{
        sound:document.querySelector('#boom'),
        key:document.querySelector("#keyZ")
    },
    KeyX:{
        sound:document.querySelector('#clap'),
        key:document.querySelector("#keyX")
    },
    KeyA:{
        sound:document.querySelector('#hihat'),
        key:document.querySelector("#keyA")
    },
    KeyS :{
        sound:document.querySelector('#openhat'),
        key:document.querySelector("#keyS")
    },
    KeyD :{
        sound:document.querySelector('#kick'),
        key:document.querySelector("#keyD")
    },
    KeyC :{
        sound:document.querySelector('#ride'),
        key:document.querySelector("#keyC"),
    },
    KeyF :{
        sound:document.querySelector('#tink'),
        key:document.querySelector("#keyF")
    },
    KeyV :{
        sound:document.querySelector('#snare'),
        key:document.querySelector("#keyV"),
    },
    KeyG :{
        sound:document.querySelector('#tom'),
        key:document.querySelector("#keyG")
    },
    Backquote:{
        key:document.querySelector("#backquote")
    },
    Digit1:{
        key:document.querySelector("#digit1")
    },
    Digit2:{
        key:document.querySelector("#digit2")
    },
    Digit3:{
        key:document.querySelector("#digit3")
    },
    Digit4:{
        key:document.querySelector("#digit4")
    },
    Digit5:{
        key:document.querySelector("#digit5")
    },
    Digit6:{
        key:document.querySelector("#digit6")
    },
    Digit7:{
        key:document.querySelector("#digit7")
    },
    Digit8:{
        key:document.querySelector("#digit8")
    },
    Digit9:{
        key:document.querySelector("#digit9")
    },
    Digit0:{
        key:document.querySelector("#digit0")
    },
    Minus:{
        key:document.querySelector("#minus")
    },
    Equal:{
        key:document.querySelector("#equal")
    },
    Backspace:{
        key:document.querySelector("#backspace")
    },
    Tab:{
        key:document.querySelector("#tab")
    },
    KeyQ:{
        key:document.querySelector('#keyQ')
    },
    KeyW:{
        key:document.querySelector('#keyW')
    },
    KeyE:{
        key:document.querySelector('#keyE')
    },
    KeyR:{
        key:document.querySelector('#keyR')
    },
    KeyT:{
        key:document.querySelector('#keyT')
    },
    KeyY:{
        key:document.querySelector('#keyY')
    },
    KeyU:{
        key:document.querySelector('#keyU')
    },
    KeyI:{
        key:document.querySelector('#keyI')
    },
    KeyP:{
        key:document.querySelector('#keyP')
    },
    KeyO:{
        key:document.querySelector('#keyO')
    },
    KeyH:{
        key:document.querySelector('#keyH')
    },
    KeyJ:{
        key:document.querySelector('#keyJ')
    },
    KeyK:{
        key:document.querySelector('#keyK')
    },
    KeyL:{
        key:document.querySelector('#keyL')
    },
    KeyB:{
        key:document.querySelector('#keyB')
    },
    KeyN:{
        key:document.querySelector('#keyN')
    },
    KeyM:{
        key:document.querySelector('#keyM')
    },
    BracketLeft:{
        key:document.querySelector('#BracketLeft')
    },
    BracketRight:{
        key:document.querySelector('#BracketRight')
    },
    Backslash:{
        key:document.querySelector('#Backslash')
    },
    CapsLock:{
        key:document.querySelector('#CapsLock')
    },
    Semicolon:{
        key:document.querySelector('#Semicolon')
    },
    Quote:{
        key:document.querySelector('#Quote')
    },
    Enter:{
        key:document.querySelector('#Enter')
    },
    ShiftLeft:{
        key:document.querySelector('#ShiftLeft')
    },
    Comma:{
        key:document.querySelector('#Comma')
    },
    Period:{
        key:document.querySelector('#Period')
    },
    Slash:{
        key:document.querySelector('#Slash')
    },
    ShiftRight:{
        key:document.querySelector('#ShiftRight')
    },
    ControlLeft:{
        key:document.querySelector('#CtrlLeft')
    },
    ControlRight:{
        key:document.querySelector('#CtrlRight')
    },
    MetaLeft:{
        key:document.querySelector('#MetaLeft')
    },
    AltLeft:{
        key:document.querySelector('#AltLeft')
    },
    AltRight:{
        key:document.querySelector('#AltRight')
    },
    Space:{
        key:document.querySelector('#Space')
    },

}